# Generated by Django 5.2.10 on 2026-01-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie de boissons',
                'verbose_name_plural': 'Catégories de boissons',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie du menu',
                'verbose_name_plural': 'Catégories du menu',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix (€)')),
                ('content', models.TextField(help_text='Détail des plats inclus', verbose_name='Contenu du menu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('available_days', models.CharField(blank=True, max_length=200, verbose_name='Jours de disponibilité')),
                ('available_hours', models.CharField(blank=True, max_length=100, verbose_name='Heures de disponibilité')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/special/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Menu spécial',
                'verbose_name_plural': 'Menus spéciaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix (€)')),
                ('volume', models.CharField(blank=True, choices=[('25cl', '25cl'), ('33cl', '33cl'), ('50cl', '50cl'), ('75cl', '75cl'), ('pint', 'Pinte'), ('half', 'Demi'), ('glass', 'Verre'), ('bottle', 'Bouteille'), ('shot', 'Shot')], max_length=20, verbose_name='Volume')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='menu.drinkcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Boisson',
                'verbose_name_plural': 'Boissons',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix (€)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Végétarien')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Végan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Sans gluten')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Épicé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('allergens', models.TextField(blank=True, verbose_name='Allergènes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Item du menu',
                'verbose_name_plural': 'Items du menu',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
    ]
