# Generated by Django 5.2.10 on 2026-01-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image de couverture')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Afficher dans le menu')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom interne')),
                ('section_type', models.CharField(choices=[('text', 'Texte simple'), ('text_image', 'Texte + Image'), ('gallery', 'Galerie'), ('cta', 'Call to Action'), ('testimonial', 'Témoignage'), ('feature', 'Feature')], default='text', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Image')),
                ('image_position', models.CharField(choices=[('left', 'Gauche'), ('right', 'Droite')], default='right', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='Texte du bouton')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL du bouton')),
                ('background_color', models.CharField(blank=True, max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(blank=True, max_length=7, verbose_name='Couleur du texte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'Section de contenu',
                'verbose_name_plural': 'Sections de contenu',
                'ordering': ['order'],
            },
        ),
    ]
