# Generated by Django 5.2.10 on 2026-01-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Couleur (hex)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône Bootstrap')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événements",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Description courte')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('doors_open', models.TimeField(blank=True, null=True, verbose_name='Ouverture des portes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='Miniature')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Prix (€)')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('ticket_url', models.URLField(blank=True, verbose_name='Lien billetterie')),
                ('artist_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'artiste")),
                ('artist_bio', models.TextField(blank=True, verbose_name="Bio de l'artiste")),
                ('artist_website', models.URLField(blank=True, verbose_name="Site de l'artiste")),
                ('artist_social', models.JSONField(blank=True, default=dict, verbose_name='Réseaux sociaux artiste')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('is_weekly_highlight', models.BooleanField(default=False, verbose_name='Événement de la semaine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
